# Generated by Django 4.2.27 on 2026-04-15 12:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models


TARGET_SUBCATEGORIES_V2 = {
    "crossbody": {
        "name": "Crossbody",
        "description": "Crossbody bag styles.",
        "aliases": ["crossbody", "crossbody-bags", "sub-1"],
    },
    "shoulder": {
        "name": "Shoulder",
        "description": "Shoulder bag styles.",
        "aliases": ["shoulder", "shoulder-bags", "sub-2"],
    },
    "top-handle": {
        "name": "Top Handle",
        "description": "Top handle bag styles.",
        "aliases": ["top-handle", "handbags", "sub-3", "sub-5"],
    },
    "evening": {
        "name": "Evening",
        "description": "Evening bag styles.",
        "aliases": ["evening", "clutches", "sub-4"],
    },
}

ALIAS_TO_CANONICAL_V2 = {
    alias: canonical
    for canonical, metadata in TARGET_SUBCATEGORIES_V2.items()
    for alias in metadata["aliases"]
}

TARGET_SUBCATEGORIES_V3 = {
    "crossbody-bags": {
        "name": "Crossbody Bags",
        "description": (
            "Long-strap bags worn across the body for hands-free, "
            "everyday comfort."
        ),
        "aliases": ["crossbody-bags", "crossbody", "sub-1"],
    },
    "shoulder-bags": {
        "name": "Shoulder Bags",
        "description": (
            "Medium-size bags designed to rest on the shoulder or under "
            "the arm."
        ),
        "aliases": ["shoulder-bags", "shoulder", "sub-2"],
    },
    "handbags": {
        "name": "Handbags",
        "description": (
            "Structured bags carried by hand or short handles for a "
            "polished look."
        ),
        "aliases": ["handbags", "top-handle", "top_handle", "sub-3", "sub-5"],
    },
    "clutches": {
        "name": "Clutches",
        "description": (
            "Compact bags without long straps, ideal for evenings and "
            "minimal carry."
        ),
        "aliases": ["clutches", "evening", "sub-4"],
    },
}

ALIAS_TO_TARGET_V3 = {
    alias: target
    for target, metadata in TARGET_SUBCATEGORIES_V3.items()
    for alias in metadata["aliases"]
}


def copy_subcategory_fk_to_m2m(apps, schema_editor):
    Product = apps.get_model('db', 'Product')
    through = Product.subcategories.through

    for product in Product.objects.exclude(subcategory_id=None).only(
        'id', 'subcategory_id'
    ).iterator():
        through.objects.get_or_create(
            product_id=product.id,
            subcategory_id=product.subcategory_id,
        )


def _mark_legacy_slug(subcategory):
    if '-old-' in subcategory.slug:
        return
    subcategory.slug = f"{subcategory.slug}-old-{subcategory.id}"
    subcategory.save(update_fields=["slug"])


def normalize_bags_taxonomy(apps, schema_editor):
    Category = apps.get_model("db", "Category")
    Subcategory = apps.get_model("db", "Subcategory")
    Product = apps.get_model("db", "Product")
    through_model = Product.subcategories.through

    bags = Category.objects.filter(slug="bags").first()
    if not bags:
        return

    used_ids = set()
    canonical_targets = {}

    for canonical_slug, metadata in TARGET_SUBCATEGORIES_V2.items():
        target = Subcategory.objects.filter(
            category_id=bags.id,
            slug=canonical_slug,
        ).first()
        if not target:
            target = (
                Subcategory.objects.filter(
                    category_id=bags.id,
                    slug__in=metadata["aliases"],
                )
                .order_by("id")
                .first()
            )
        if not target:
            target = Subcategory.objects.create(
                category_id=bags.id,
                name=metadata["name"],
                slug=canonical_slug,
                description=metadata["description"],
            )
        canonical_targets[canonical_slug] = target
        used_ids.add(target.id)

    for canonical_slug, target in canonical_targets.items():
        metadata = TARGET_SUBCATEGORIES_V2[canonical_slug]
        if target.slug != canonical_slug:
            existing = Subcategory.objects.filter(
                category_id=bags.id,
                slug=canonical_slug,
            ).exclude(id=target.id).first()
            if existing:
                _mark_legacy_slug(target)
                target = existing
                canonical_targets[canonical_slug] = target
                used_ids.add(target.id)
            else:
                target.slug = canonical_slug
        target.name = metadata["name"]
        target.description = metadata["description"]
        target.save()

    bags_subcategories = list(Subcategory.objects.filter(category_id=bags.id).order_by("id"))
    for subcategory in bags_subcategories:
        if subcategory.id in used_ids:
            continue
        canonical_slug = ALIAS_TO_CANONICAL_V2.get(subcategory.slug)
        if canonical_slug:
            target = canonical_targets[canonical_slug]
            through_model.objects.filter(subcategory_id=subcategory.id).update(
                subcategory_id=target.id
            )
            if subcategory.slug != target.slug:
                _mark_legacy_slug(subcategory)


def restore_legacy_bags_taxonomy(apps, schema_editor):
    Category = apps.get_model("db", "Category")
    Subcategory = apps.get_model("db", "Subcategory")
    Product = apps.get_model("db", "Product")
    through_model = Product.subcategories.through

    bags = Category.objects.filter(slug="bags").first()
    if not bags:
        return

    chosen_targets = {}
    used_ids = set()

    for target_slug, metadata in TARGET_SUBCATEGORIES_V3.items():
        target = Subcategory.objects.filter(
            category_id=bags.id,
            slug=target_slug,
        ).first()
        if not target:
            target = (
                Subcategory.objects.filter(
                    category_id=bags.id,
                    slug__in=metadata["aliases"],
                )
                .exclude(slug__contains="-old-")
                .order_by("id")
                .first()
            )

        if target and target.slug != target_slug:
            conflict = Subcategory.objects.filter(
                category_id=bags.id,
                slug=target_slug,
            ).exclude(id=target.id).first()
            if conflict:
                target = conflict
            else:
                target.slug = target_slug

        if not target:
            target = Subcategory.objects.create(
                category_id=bags.id,
                name=metadata["name"],
                slug=target_slug,
                description=metadata["description"],
            )

        target.name = metadata["name"]
        target.description = metadata["description"]
        target.save()

        chosen_targets[target_slug] = target
        used_ids.add(target.id)

    for subcategory in Subcategory.objects.filter(category_id=bags.id).order_by("id"):
        if subcategory.id in used_ids:
            continue
        target_slug = ALIAS_TO_TARGET_V3.get(subcategory.slug)
        if not target_slug:
            continue
        target = chosen_targets[target_slug]
        through_model.objects.filter(subcategory_id=subcategory.id).update(
            subcategory_id=target.id
        )
        if subcategory.slug != target.slug:
            _mark_legacy_slug(subcategory)

class Migration(migrations.Migration):

    replaces = [('db', '0001_initial'), ('db', '0002_homesection_homesectionitem_and_more'), ('db', '0003_product_variant_color_name_and_more'), ('db', '0004_subcategory_description_m2m'), ('db', '0005_remove_product_products_subcate_db3262_idx'), ('db', '0006_product_products_categor_8c32e2_idx_and_more'), ('db', '0007_normalize_bags_taxonomy_contract'), ('db', '0008_restore_bags_contract_legacy_labels'), ('db', '0009_category_image_subcategory_image')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('category', 'Category'), ('subcategory', 'Subcategory')], max_length=20)),
                ('scope_id', models.IntegerField()),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'db_table': 'attributes',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.attribute')),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'db_table': 'attribute_options',
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_new', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order')], default='in_stock', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='db.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('color_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='db.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='db.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Size',
                'verbose_name_plural': 'Variant Sizes',
                'db_table': 'variant_sizes',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='db.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'db_table': 'subcategories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='db.product')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'db_table': 'product_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.attributeoption')),
                ('product_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='db.productattributevalue')),
            ],
            options={
                'verbose_name': 'Product Attribute Option',
                'verbose_name_plural': 'Product Attribute Options',
                'db_table': 'product_attribute_options',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='db.subcategory'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['scope_type', 'scope_id'], name='attributes_scope_t_651bc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('scope_type', 'scope_id', 'key')},
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='variantsize',
            unique_together={('variant', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributeoption',
            unique_together={('product_attribute_value', 'option')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'availability'], name='products_categor_b5989c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'value')},
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.URLField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_count', models.IntegerField(default=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'db_table': 'home_sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='db.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.homesection')),
            ],
            options={
                'verbose_name': 'Home Section Item',
                'verbose_name_plural': 'Home Section Items',
                'db_table': 'home_section_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='homesection',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_sectio_is_acti_afcbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='homesectionitem',
            index=models.Index(fields=['section', 'sort_order'], name='home_sectio_section_1b43b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='homesectionitem',
            unique_together={('section', 'product')},
        ),
        migrations.AddField(
            model_name='product',
            name='variant_color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_color_palette',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_variant_groups', to='db.product')),
            ],
            options={
                'verbose_name': 'Variant Group',
                'verbose_name_plural': 'Variant Groups',
                'db_table': 'variant_groups',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='db.variantgroup'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='db.subcategory'),
        ),
        migrations.RunPython(
            code=copy_subcategory_fk_to_m2m,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='products_categor_8c32e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability', '-created_at'], name='products_availab_aabb89_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'sort_order'], name='product_var_product_15ccb4_idx'),
        ),
        migrations.RunPython(
            code=normalize_bags_taxonomy,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=restore_legacy_bags_taxonomy,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
