# Generated by Django 4.2.27 on 2025-12-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', models.URLField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_count', models.IntegerField(default=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'db_table': 'home_sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='db.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.homesection')),
            ],
            options={
                'verbose_name': 'Home Section Item',
                'verbose_name_plural': 'Home Section Items',
                'db_table': 'home_section_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='homesection',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_sectio_is_acti_afcbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='homesectionitem',
            index=models.Index(fields=['section', 'sort_order'], name='home_sectio_section_1b43b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='homesectionitem',
            unique_together={('section', 'product')},
        ),
    ]
