# Generated by Django 4.2.27 on 2025-12-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_homesection_homesectionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_color_palette',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_variant_groups', to='db.product')),
            ],
            options={
                'verbose_name': 'Variant Group',
                'verbose_name_plural': 'Variant Groups',
                'db_table': 'variant_groups',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='db.variantgroup'),
        ),
    ]
