# Generated by Django 4.2 on 2026-01-28

from django.db import migrations, models


def copy_subcategory_fk_to_m2m(apps, schema_editor):
    Product = apps.get_model('db', 'Product')
    through = Product.subcategories.through

    for product in Product.objects.exclude(subcategory_id=None).only(
        'id', 'subcategory_id'
    ).iterator():
        through.objects.get_or_create(
            product_id=product.id,
            subcategory_id=product.subcategory_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_product_variant_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(
                blank=True,
                related_name='products',
                to='db.subcategory',
            ),
        ),
        migrations.RunPython(copy_subcategory_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS products_subcate_db3262_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
