# Generated by Django 4.2.27 on 2026-03-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_subcategory_description_m2m'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_subcate_db3262_idx',
        ),
    ]
