# Generated by Django 4.2.27 on 2026-04-15
from django.db import migrations


TARGET_SUBCATEGORIES = {
    "crossbody": {
        "name": "Crossbody",
        "description": "Crossbody bag styles.",
        "aliases": ["crossbody", "crossbody-bags", "sub-1"],
    },
    "shoulder": {
        "name": "Shoulder",
        "description": "Shoulder bag styles.",
        "aliases": ["shoulder", "shoulder-bags", "sub-2"],
    },
    "top-handle": {
        "name": "Top Handle",
        "description": "Top handle bag styles.",
        "aliases": ["top-handle", "handbags", "sub-3", "sub-5"],
    },
    "evening": {
        "name": "Evening",
        "description": "Evening bag styles.",
        "aliases": ["evening", "clutches", "sub-4"],
    },
}

ALIAS_TO_CANONICAL = {
    alias: canonical
    for canonical, metadata in TARGET_SUBCATEGORIES.items()
    for alias in metadata["aliases"]
}


def _mark_legacy_slug(subcategory):
    subcategory.slug = f"{subcategory.slug}-old-{subcategory.id}"
    subcategory.save(update_fields=["slug"])


def normalize_bags_taxonomy(apps, schema_editor):
    Category = apps.get_model("db", "Category")
    Subcategory = apps.get_model("db", "Subcategory")
    Product = apps.get_model("db", "Product")
    through_model = Product.subcategories.through

    bags = Category.objects.filter(slug="bags").first()
    if not bags:
        return

    used_ids = set()
    canonical_targets = {}

    for canonical_slug, metadata in TARGET_SUBCATEGORIES.items():
        target = Subcategory.objects.filter(
            category_id=bags.id,
            slug=canonical_slug,
        ).first()
        if not target:
            target = (
                Subcategory.objects.filter(
                    category_id=bags.id,
                    slug__in=metadata["aliases"],
                )
                .order_by("id")
                .first()
            )
        if not target:
            target = Subcategory.objects.create(
                category_id=bags.id,
                name=metadata["name"],
                slug=canonical_slug,
                description=metadata["description"],
            )
        canonical_targets[canonical_slug] = target
        used_ids.add(target.id)

    # Normalize canonical rows to stable slug/name/description.
    for canonical_slug, target in canonical_targets.items():
        metadata = TARGET_SUBCATEGORIES[canonical_slug]
        if target.slug != canonical_slug:
            existing = Subcategory.objects.filter(
                category_id=bags.id,
                slug=canonical_slug,
            ).exclude(id=target.id).first()
            if existing:
                _mark_legacy_slug(target)
                target = existing
                canonical_targets[canonical_slug] = target
                used_ids.add(target.id)
            else:
                target.slug = canonical_slug
        target.name = metadata["name"]
        target.description = metadata["description"]
        target.save()

    # Repoint alias rows to canonical targets, then hide them as legacy.
    bags_subcategories = list(Subcategory.objects.filter(category_id=bags.id).order_by("id"))
    for subcategory in bags_subcategories:
        if subcategory.id in used_ids:
            continue
        canonical_slug = ALIAS_TO_CANONICAL.get(subcategory.slug)
        if canonical_slug:
            target = canonical_targets[canonical_slug]
            through_model.objects.filter(subcategory_id=subcategory.id).update(
                subcategory_id=target.id
            )
            if subcategory.slug != target.slug:
                _mark_legacy_slug(subcategory)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_product_products_categor_8c32e2_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_bags_taxonomy, migrations.RunPython.noop),
    ]
