# Generated by Django 4.2.27 on 2026-04-15
from django.db import migrations


TARGET_SUBCATEGORIES = {
    "crossbody-bags": {
        "name": "Crossbody Bags",
        "description": (
            "Long-strap bags worn across the body for hands-free, "
            "everyday comfort."
        ),
        "aliases": ["crossbody-bags", "crossbody", "sub-1"],
    },
    "shoulder-bags": {
        "name": "Shoulder Bags",
        "description": (
            "Medium-size bags designed to rest on the shoulder or under "
            "the arm."
        ),
        "aliases": ["shoulder-bags", "shoulder", "sub-2"],
    },
    "handbags": {
        "name": "Handbags",
        "description": (
            "Structured bags carried by hand or short handles for a "
            "polished look."
        ),
        "aliases": ["handbags", "top-handle", "top_handle", "sub-3", "sub-5"],
    },
    "clutches": {
        "name": "Clutches",
        "description": (
            "Compact bags without long straps, ideal for evenings and "
            "minimal carry."
        ),
        "aliases": ["clutches", "evening", "sub-4"],
    },
}

ALIAS_TO_TARGET = {
    alias: target
    for target, metadata in TARGET_SUBCATEGORIES.items()
    for alias in metadata["aliases"]
}


def _mark_legacy_slug(subcategory):
    if "-old-" in subcategory.slug:
        return
    subcategory.slug = f"{subcategory.slug}-old-{subcategory.id}"
    subcategory.save(update_fields=["slug"])


def restore_legacy_bags_taxonomy(apps, schema_editor):
    Category = apps.get_model("db", "Category")
    Subcategory = apps.get_model("db", "Subcategory")
    Product = apps.get_model("db", "Product")
    through_model = Product.subcategories.through

    bags = Category.objects.filter(slug="bags").first()
    if not bags:
        return

    chosen_targets = {}
    used_ids = set()

    # Ensure each target slug exists and points to one canonical row.
    for target_slug, metadata in TARGET_SUBCATEGORIES.items():
        target = Subcategory.objects.filter(
            category_id=bags.id,
            slug=target_slug,
        ).first()
        if not target:
            target = (
                Subcategory.objects.filter(
                    category_id=bags.id,
                    slug__in=metadata["aliases"],
                )
                .exclude(slug__contains="-old-")
                .order_by("id")
                .first()
            )

        if target and target.slug != target_slug:
            # Avoid unique collisions when setting target slug.
            conflict = Subcategory.objects.filter(
                category_id=bags.id,
                slug=target_slug,
            ).exclude(id=target.id).first()
            if conflict:
                target = conflict
            else:
                target.slug = target_slug

        if not target:
            target = Subcategory.objects.create(
                category_id=bags.id,
                name=metadata["name"],
                slug=target_slug,
                description=metadata["description"],
            )

        target.name = metadata["name"]
        target.description = metadata["description"]
        target.save()

        chosen_targets[target_slug] = target
        used_ids.add(target.id)

    # Repoint all alias rows to the chosen canonical targets, then legacy-tag extras.
    for subcategory in Subcategory.objects.filter(category_id=bags.id).order_by("id"):
        if subcategory.id in used_ids:
            continue
        target_slug = ALIAS_TO_TARGET.get(subcategory.slug)
        if not target_slug:
            continue
        target = chosen_targets[target_slug]
        through_model.objects.filter(subcategory_id=subcategory.id).update(
            subcategory_id=target.id
        )
        if subcategory.slug != target.slug:
            _mark_legacy_slug(subcategory)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_normalize_bags_taxonomy_contract"),
    ]

    operations = [
        migrations.RunPython(restore_legacy_bags_taxonomy, migrations.RunPython.noop),
    ]
