# Generated by Django 4.2.27 on 2026-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_restore_bags_contract_legacy_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
