# Generated by Django 4.2.27 on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0010_product_description_productvariant_care_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'image_url',
                    models.URLField(blank=True, null=True),
                ),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'variant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='db.productvariant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product Variant Image',
                'verbose_name_plural': 'Product Variant Images',
                'db_table': 'product_variant_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariantimage',
            index=models.Index(fields=['variant', 'sort_order', 'id'], name='prod_var_img_var_sort_id_idx'),
        ),
    ]

