# Generated by Django 4.2.27 on 2026-05-05

from django.db import migrations


def forward_backfill_variant_images(apps, schema_editor):
    ProductVariant = apps.get_model('db', 'ProductVariant')
    ProductVariantImage = apps.get_model('db', 'ProductVariantImage')

    variants = ProductVariant.objects.exclude(image_url__isnull=True).exclude(
        image_url=''
    )

    for variant in variants.iterator():
        existing = ProductVariantImage.objects.filter(
            variant_id=variant.id,
            image_url=variant.image_url,
        ).exists()
        if existing:
            continue

        ProductVariantImage.objects.create(
            variant_id=variant.id,
            image_url=variant.image_url,
            alt='',
            sort_order=0,
            is_primary=True,
        )


def reverse_backfill_variant_images(apps, schema_editor):
    ProductVariant = apps.get_model('db', 'ProductVariant')
    ProductVariantImage = apps.get_model('db', 'ProductVariantImage')

    variants = ProductVariant.objects.exclude(image_url__isnull=True).exclude(
        image_url=''
    )
    variant_ids = list(variants.values_list('id', flat=True))
    if not variant_ids:
        return

    ProductVariantImage.objects.filter(
        variant_id__in=variant_ids,
        sort_order=0,
        is_primary=True,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0011_add_product_variant_images'),
    ]

    operations = [
        migrations.RunPython(
            forward_backfill_variant_images,
            reverse_backfill_variant_images,
        ),
    ]

